name       : libva
version    : 1.5.0
release    : 3
source     :
    - http://freedesktop.org/software/vaapi/releases/libva/libva-1.5.0.tar.bz2 : e946d4b3110e4e23ec6a588e0c828937e502c67196d1266214441fefc4b83486
license    : MIT
summary    : Video Acceleration (VA) API for Linux
description: |
    Video Acceleration (VA) API for Linux
builddeps  :
    - pkgconfig32(x11)
    - pkgconfig32(xext)
    - pkgconfig32(xfixes)
    - pkgconfig32(libdrm)
    - pkgconfig32(wayland-client)
    - pkgconfig32(gl)
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
emul32     : yes
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
    %make clean
