name       : libva
version    : 2.8.0
release    : 16
source     :
    - https://github.com/intel/libva/releases/download/2.8.0/libva-2.8.0.tar.bz2 : adbb1244d278908f89ccfcf254a442de6d71934565a492cb6f03caf2ed4d1ec3
license    : MIT
component  : xorg.display
summary    : Libva is an implementation for VA-API (Video Acceleration API)
description: |
    VA-API is an open-source library and API specification, which provides access to graphics hardware acceleration capabilities for video processing. It consists of a main library and driver-specific acceleration backends for each supported hardware vendor.
builddeps  :
    - pkgconfig32(gl)
    - pkgconfig32(libdrm)
    - pkgconfig32(wayland-client)
    - pkgconfig32(x11)
    - pkgconfig32(xext)
    - pkgconfig32(xfixes)
emul32     : yes
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
