name       : libva
version    : 2.14.0
release    : 22
source     :
    - https://github.com/intel/libva/releases/download/2.14.0/libva-2.14.0.tar.bz2 : 511e9a74d1ccfb548bc192290603082c11074ac59b17aadfd5d56a3f93e58454
license    : MIT
component  : xorg.display
summary    : Libva is an implementation for VA-API (Video Acceleration API)
description: |
    VA-API is an open-source library and API specification, which provides access to graphics hardware acceleration capabilities for video processing. It consists of a main library and driver-specific acceleration backends for each supported hardware vendor.
builddeps  :
    - pkgconfig32(gl)
    - pkgconfig32(libdrm)
    - pkgconfig32(wayland-client)
    - pkgconfig32(x11)
    - pkgconfig32(xext)
    - pkgconfig32(xfixes)
emul32     : yes
setup      : |
    %patch -p1 < $pkgfiles/add-nvidia-to-libva-driver-map.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
