name       : libva
version    : 2.17.0
release    : 25
source     :
    - https://github.com/intel/libva/archive/refs/tags/2.17.0.tar.gz : 8940541980ef998a36cd8f6ad905e81838ea4ddf56dc479ed2bebd12711e6001
license    : MIT
component  : xorg.display
summary    : Libva is an implementation for VA-API (Video Acceleration API)
description: |
    VA-API is an open-source library and API specification, which provides access to graphics hardware acceleration capabilities for video processing. It consists of a main library and driver-specific acceleration backends for each supported hardware vendor.
builddeps  :
    - pkgconfig32(gl)
    - pkgconfig32(libdrm)
    - pkgconfig32(wayland-client)
    - pkgconfig32(x11)
    - pkgconfig32(xext)
    - pkgconfig32(xfixes)
emul32     : yes
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
