name       : libva
version    : 1.5.0
release    : 1
source     :
    - http://freedesktop.org/software/vaapi/releases/libva/libva-1.5.0.tar.bz2 : e946d4b3110e4e23ec6a588e0c828937e502c67196d1266214441fefc4b83486
license    : MIT
summary    : Video Acceleration (VA) API for Linux
description: |
    Video Acceleration (VA) API for Linux
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
    - pkgconfig(gl)
    - pkgconfig(egl)
    - pkgconfig(wayland-client)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
