name       : libva
version    : 2.0.0
release    : 7
source     :
    - https://github.com/01org/libva/releases/download/2.0.0/libva-2.0.0.tar.bz2 : bb0601f9a209e60d8d0b867067323661a7816ff429021441b775452b8589e533
license    : MIT
component  : xorg.display
summary    : Video Acceleration (VA) API for Linux
description: |
    Video Acceleration (VA) API for Linux
builddeps  :
    - pkgconfig32(gl)
    - pkgconfig32(libdrm)
    - pkgconfig32(wayland-client)
    - pkgconfig32(x11)
    - pkgconfig32(xext)
    - pkgconfig32(xfixes)
emul32     : yes
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
