name       : libva
version    : 2.3.0
release    : 11
source     :
    - https://github.com/intel/libva/archive/2.3.0.tar.gz : 8d95e65c4d84d0f82097581e163d3770694c600cbb040ebd827f2d375e004f4b
license    : MIT
component  : xorg.display
summary    : Video Acceleration (VA) API for Linux
description: |
    Video Acceleration (VA) API for Linux
builddeps  :
    - pkgconfig32(gl)
    - pkgconfig32(libdrm)
    - pkgconfig32(wayland-client)
    - pkgconfig32(x11)
    - pkgconfig32(xext)
    - pkgconfig32(xfixes)
emul32     : yes
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
