name       : libva
version    : 1.8.1
release    : 6
source     :
    - https://freedesktop.org/software/vaapi/releases/libva/libva-1.8.1.tar.bz2 : c1d5d85b6b40b76f37993b4da33388d3d73b64998dcbc160b7578e24ed775c73
license    : MIT
component  : xorg.display
summary    : Video Acceleration (VA) API for Linux
description: |
    Video Acceleration (VA) API for Linux
builddeps  :
    - pkgconfig32(x11)
    - pkgconfig32(xext)
    - pkgconfig32(xfixes)
    - pkgconfig32(libdrm)
    - pkgconfig32(wayland-client)
    - pkgconfig32(gl)
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
emul32     : yes
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
    %make clean
