name       : libva
version    : 2.1.0
release    : 9
source     :
    - https://github.com/intel/libva/releases/download/2.1.0/libva-2.1.0.tar.bz2 : f3fa953a11d3210c3a4ee79031abdbe0863d5ce13d9b3f93f315f1eec60a4b0f
license    : MIT
component  : xorg.display
summary    : Video Acceleration (VA) API for Linux
description: |
    Video Acceleration (VA) API for Linux
builddeps  :
    - pkgconfig32(gl)
    - pkgconfig32(libdrm)
    - pkgconfig32(wayland-client)
    - pkgconfig32(x11)
    - pkgconfig32(xext)
    - pkgconfig32(xfixes)
emul32     : yes
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
